---
title: "Fig4"
output: html_document
date: "2025-09-03"
---
```{r}
library(monocle3)
library(Seurat)
library(SeuratWrappers)
library(ggplot2)
library(patchwork)
library(tibble)
library(ggbeeswarm)
library(dplyr)
library(tidyr)
library(tidyverse)
```

```{r}
#Figure 4A
#Monocle3 Analysis in EVTLineage
EVTlineage <- subset (organoids, idents = c("CTB 1", "CTB 2", "cCTB", "EVT"))
rm(organoids)
EVT.monocle3 <- as.cell_data_set(EVTlineage, assay = "RNA")
rm(EVTlineage)
EVT.monocle3 <- estimate_size_factors (EVT.monocle3)
EVT.monocle3 <- cluster_cells         (EVT.monocle3,
                                       reduction_method = c("UMAP"),
                                       cluster_method   = "leiden",
                                       partition_qval   = 0.05,
                                       resolution       = 0.00025)

p1  <- plot_cells (EVT.monocle3,                               show_trajectory_graph = FALSE)
p2  <- plot_cells (EVT.monocle3, color_cells_by = "partition", show_trajectory_graph = FALSE)
wrap_plots        (p1, p2)
EVT.monocle3 <- learn_graph (EVT.monocle3, use_partition = FALSE, close_loop = TRUE)
get_earliest_principal_node <- function(EVT.monocle3, time_bin="1"){
  cell_ids <- which(colData(EVT.monocle3)[, "Time"] == time_bin)
  
  closest_vertex <-
  EVT.monocle3@principal_graph_aux[["UMAP"]]$pr_graph_cell_proj_closest_vertex
  closest_vertex <- as.matrix(closest_vertex[colnames(EVT.monocle3), ])
  root_pr_nodes <-
  igraph::V(principal_graph(EVT.monocle3)[["UMAP"]])$name[as.numeric(names
  (which.max(table(closest_vertex[cell_ids,]))))]
  
  root_pr_nodes
}
EVT.monocle3 <- order_cells(EVT.monocle3, root_pr_nodes=get_earliest_principal_node(EVT.monocle3))
#Add pseudotime values back into Seurat object
EVT.monocle3$monocle3_pseudotime <- pseudotime(EVT.monocle3)
EVTlineage$pseudotime <- pseudotime(EVT.monocle3)
#EVTLineage UMAP
pdf         ("UMAP_EVTLineage.pdf", height = 5, width = 9)
UMAPPlot(EVTlineage, label=FALSE, order= TRUE, pt.size = 1, 
         cols    = c('CTB 1'  = '#00C19A',
                      'CTB 2'  = '#999999',
                      'cCTB'   = '#AE017E',
                      'EVT'    = '#FFD92F'))
dev.off     ()
#EVTLineage Monocle3 UMAP
pdf         ("UMAP_Monocle3.pdf", height = 5, width = 9)
plot_cells (EVT.monocle3,
            color_cells_by = "pseudotime",
            label_cell_groups             = FALSE,
            label_leaves                  = FALSE,
            label_branch_points           = FALSE,
            graph_label_size              = 0,
            cell_size                     = 1,
            trajectory_graph_color        = "black",
            trajectory_graph_segment_size = 1)
dev.off     ()
```

```{r}
#Figure 4B
EVTlineage <- SetIdent(EVTlineage, value = EVTlineage@meta.data$OxygenCondition)
EVT.monocle3 <- as.cell_data_set(EVTlineage, assay = "RNA")
pt_df_sdz <- data.frame(
  pseudotime = colData(EVT.monocle3)$pseudotime,
  Condition = colData(EVT.monocle3)$OxygenCondition,
  cell_type = colData(EVT.monocle3)$celltype
)
cell_type_colors <- c(
  'CTB 1'  = '#00C19A',
  'CTB 2'  = '#999999',
  'cCTB'   = '#AE017E',
  'EVT'    = '#FFD92F')

condition_colors <- c(
  "20" = "darkorchid",
  "3" = "blue",
  "8" = "palegreen1")
pdf         ("DensityPlot.pdf", height = 7, width = 10)
ggplot(pt_df_sdz, aes(x = pseudotime, y = Condition)) +
  geom_quasirandom(
    aes(color = cell_type),
    groupOnX = FALSE,
    varwidth = FALSE,
    size = 1,
    alpha = 1
  ) +
  scale_color_manual(values = cell_type_colors) +
  labs(x = NULL, y = "Condition", color = "Cell Type") +
  theme_minimal(base_size = 13) +
  theme(
    legend.position = "right",
    panel.grid.major.y = element_blank(),
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.title.y = element_text(angle = 90, vjust = 0.5),
    axis.text.y = element_text(size = 10),
    plot.margin = margin(0, 10, 0, 10)
  )+ NoLegend()
dev.off     ()

pdf         ("DensityLineGraph.pdf", height = 7, width = 10)
ggplot(pt_df_sdz, aes(x = pseudotime, color = Condition)) +
  geom_density(size = 1.5) +
  scale_color_manual(values = condition_colors) +
  labs(x = "Pseudotime", y = "Density") +
  theme_minimal(base_size = 13) +
  theme(
    legend.position = "none",
    plot.margin = margin(0, 10, 0, 10)
  )
dev.off     ()
```

```{r}
#Significance Testing
kruskal.test(pseudotime ~ OxygenCondition, data = EVTlineage@meta.data)

# Run pairwise Wilcoxon test
pw <- pairwise.wilcox.test(
  EVTlineage$pseudotime,
  EVTlineage$OxygenCondition,
  p.adjust.method = "BH"
)
```

```{r}
#Figure 4C
#Make the 3%, 8%, and 21% Objects
EVTlineage <- SetIdent(EVTlineage, value = EVTlineage@meta.data$OxygenCondition)
Three <- subset (EVTlineage, idents = "3")
Three[["RNA"]] <- as(Three[["RNA"]], Class="Assay")
Three <- SetIdent(Three, value = Three@meta.data$celltype)
EVTlineage <- SetIdent(EVTlineage, value = EVTlineage@meta.data$OxygenCondition)
TwentyOne <- subset (EVTlineage, idents = "20")
TwentyOne[["RNA"]] <- as(TwentyOne[["RNA"]], Class="Assay")
TwentyOne <- SetIdent(TwentyOne, value = TwentyOne@meta.data$celltype)
EVTlineage <- SetIdent(EVTlineage, value = EVTlineage@meta.data$OxygenCondition)
Eight <- subset (EVTlineage, idents = "8")
Eight[["RNA"]] <- as(Eight[["RNA"]], Class="Assay")
Eight <- SetIdent(Eight, value = Eight@meta.data$celltype)
Three <- RenameIdents (Three, `CTB 1` = "#00C19A", `CTB 2` = "#999999",`cCTB` ="#AE017E", `EVT` = "#FFD92F")
Eight <- RenameIdents (Eight, `CTB 1` = "#00C19A", `CTB 2` = "#999999",`cCTB` ="#AE017E", `EVT` = "#FFD92F")
TwentyOne <- RenameIdents (TwentyOne, `CTB 1` = "#00C19A", `CTB 2` = "#999999",`cCTB` ="#AE017E", `EVT` = "#FFD92F")

#Example analysis for one gene (HLA-G)
GENE       <- as.data.frame      (Three@assays$RNA@counts["HLA-G", ])
GENE       <- rownames_to_column (GENE,  "Cell")
State      <- as.data.frame      (Idents (Three))
State      <- rownames_to_column (State, "Cell")
Plot       <- merge              (GENE, State, by = "Cell")
Plot       <- rownames_to_column (Plot,  "#")
Pseudotime <- as.data.frame      (Three@meta.data$pseudotime)
Pseudotime <- rownames_to_column (Pseudotime, "#")
Plot       <- merge              (Plot, Pseudotime, by = "#")
Plot       <- column_to_rownames (Plot, "#")
Plot       <- remove_rownames    (Plot)
Plot       <- column_to_rownames (Plot, "Cell")
Plot
pdf         ("HLA-G_Three_Exp.pdf", height = 9, width = 10)
ggplot      (Plot,
             aes (x = Three@meta.data$pseudotime,
                  y = Three@assays$RNA@counts["HLA-G", ])) +
geom_point  (colour = Idents(Three), size  = 4) +
geom_smooth (colour = "black", size = 4) +
xlim        (0, 35) +                             
xlab        ("Pseudotime") +                      
ylim        (0, 250) +                             
ylab        ("Expression") +
theme       (axis.line  = element_line (size = 1, colour = "black"),
             axis.ticks = element_line (size = 1, colour = "black")) +
theme       (panel.background = element_blank ())
dev.off     ()

GENE       <- as.data.frame      (TwentyOne@assays$RNA@counts["HLA-G", ])
GENE       <- rownames_to_column (GENE,  "Cell")
State      <- as.data.frame      (Idents (TwentyOne))
State      <- rownames_to_column (State, "Cell")
Plot       <- merge              (GENE, State, by = "Cell")
Plot       <- rownames_to_column (Plot,  "#")
Pseudotime <- as.data.frame      (TwentyOne@meta.data$pseudotime)
Pseudotime <- rownames_to_column (Pseudotime, "#")
Plot       <- merge              (Plot, Pseudotime, by = "#")
Plot       <- column_to_rownames (Plot, "#")
Plot       <- remove_rownames    (Plot)
Plot       <- column_to_rownames (Plot, "Cell")
Plot

pdf         ("HLA-G_TwentyOne_Exp.pdf", height = 9, width = 10)
ggplot      (Plot,
             aes (x = TwentyOne@meta.data$pseudotime,
                  y = TwentyOne@assays$RNA@counts["HLA-G", ])) +
geom_point  (colour = Idents(TwentyOne), size  = 4) +
geom_smooth (colour = "black", size = 4) +
xlim        (0, 35) +                            
xlab        ("Pseudotime") +                      
ylim        (0, 250) +                             
ylab        ("Expression") +
theme       (axis.line  = element_line (size = 1, colour = "black"),
             axis.ticks = element_line (size = 1, colour = "black")) +
theme       (panel.background = element_blank ())
dev.off     ()

GENE       <- as.data.frame      (Eight@assays$RNA@counts["HLA-G", ])
GENE       <- rownames_to_column (GENE,  "Cell")
State      <- as.data.frame      (Idents (Eight))
State      <- rownames_to_column (State, "Cell")
Plot       <- merge              (GENE, State, by = "Cell")
Plot       <- rownames_to_column (Plot,  "#")
Pseudotime <- as.data.frame      (Eight@meta.data$pseudotime)
Pseudotime <- rownames_to_column (Pseudotime, "#")
Plot       <- merge              (Plot, Pseudotime, by = "#")
Plot       <- column_to_rownames (Plot, "#")
Plot       <- remove_rownames    (Plot)
Plot       <- column_to_rownames (Plot, "Cell")
Plot

pdf         ("HLA-G_Eight_Exp.pdf", height = 9, width = 10)
ggplot      (Plot,
             aes (x = Eight@meta.data$pseudotime,
                  y = Eight@assays$RNA@counts["HLA-G", ])) +
geom_point  (colour = Idents(Eight), size  = 4) +
geom_smooth (colour = "black", size = 4) +
xlim        (0, 35) +                             
xlab        ("Pseudotime") +                      
ylim        (0, 250) +                             
ylab        ("Expression") +
theme       (axis.line  = element_line (size = 1, colour = "black"),
             axis.ticks = element_line (size = 1, colour = "black")) +
theme       (panel.background = element_blank ())
dev.off     ()
```

```{r}
#Figure 4D
#Adding a condition.Time metadata
EVTlineage <- SetIdent(EVTlineage, value = EVTlineage@meta.data$OxygenCondition)
EVTlineage$condition.Time  <- paste       (Idents (EVTlineage), EVTlineage$Time, sep = "_")
EVTlineage$OxygenCondition        <- Idents      (EVTlineage)
       Idents (EVTlineage) <- "condition.Time"
Idents(EVTlineage) <- factor(Idents(EVTlineage),
                            levels = c("20_1",  "3_1","20_2",  "8_2",  "3_2", "20_3",  "8_3",  "3_3"))


pdf("cCTB_EVT_Time.pdf", width = 7, height = 5)
DotPlot (EVTlineage,
         features  = c("TEAD4", "NOTCH1", "TAGLN", "ITGA2", "ITGB6", "HLA-G", "ITGA5", "SERPINE2", "ITGA1", "NOTUM"),
         assay     = "RNA",
         cols      = c("lightgrey", "red"),
         col.min   = 0,
         col.max   = 1,
         dot.min   = 0,
         dot.scale = 15)
dev.off
```



